ARG tag=1.13.1-py3

FROM tensorflow/tensorflow:$tag

ENV KAGGLE_CONFIG_DIR=/tmp/.kaggle
VOLUME $KAGGLE_CONFIG_DIR

RUN apt-get update && \
      apt-get install -y --no-install-recommends p7zip-full ffmpeg && \
      pip install kaggle && \
      rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY src/ /workspace
